import { deepStrictEqual, ok, strictEqual } from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, it } from "node:test";
import type { ClusterFix, DuplicateSnapshot } from "pm-dedup-core";
import { applyClusterFixes } from "./applyClusterFixes.ts";
import { createTempProjects } from "./helpers/tempProjects.ts";

const fix = (overrides: Partial<ClusterFix>): ClusterFix => ({
  members: [],
  duplicatedMembers: [],
  memberVersions: {},
  target: null,
  direction: "none",
  convergentMembers: [],
  driverMembers: [],
  excludedMembers: [],
  anchor: null,
  reuseFixes: [],
  floatingMembers: [],
  workspaceChanges: [],
  reResolutionSet: [],
  externalConstraints: [],
  needsRoundTrip: false,
  applicable: false,
  ...overrides,
});

const manifestContent = [
  "{",
  '  "name": "root",',
  '  "devDependencies": {',
  '    "metro": "0.84.5"',
  "  }",
  "}",
  "",
].join("\n");

const emptyLock = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
`;

const projects = createTempProjects("yarn-berry-deduplicate-apply-");

afterEach(projects.cleanup);

const makeProject = (): string => {
  const dir = projects.create();
  writeFileSync(join(dir, "package.json"), manifestContent);
  writeFileSync(join(dir, "yarn.lock"), emptyLock);
  return dir;
};

const read = (dir: string, name: string): string =>
  readFileSync(join(dir, name), "utf8");

const snapshot = (...resolutions: string[]): DuplicateSnapshot =>
  new Set(resolutions);

const metroFix = fix({
  applicable: true,
  target: "0.87.0",
  convergentMembers: ["metro-config"],
  workspaceChanges: [
    {
      requester: "package.json in devDependencies",
      requesterName: undefined,
      packageName: "metro",
      range: "0.84.5",
      to: "0.87.0",
      workspace: { path: "", depType: "devDependencies" },
    },
  ],
});

const leafFix = fix({
  applicable: true,
  target: "2.0.0",
  convergentMembers: ["leaf"],
});

describe("applyClusterFixes", () => {
  it("keeps the workspace edit and writes no resolution when it is enough", () => {
    const dir = makeProject();

    let duplicates = snapshot(
      "metro-config@npm:0.84.5",
      "metro-config@npm:0.87.0",
    );
    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: () => undefined,
      readFixes: () => [metroFix],
      readDuplicates: () => duplicates,
      verifyFrozen: () => 0,
      resolve: () => {
        // yarn's part: with the pin widened, the 0.84.5 subtree has no reason
        // to exist any more
        if (read(dir, "package.json").includes('"metro": "0.87.0"')) {
          duplicates = snapshot();
        }
        return 0;
      },
    });

    strictEqual(outcome.status, "applied");
    strictEqual(outcome.after.size, 0);
    ok(read(dir, "package.json").includes('"metro": "0.87.0"'));
    ok(!read(dir, "package.json").includes("resolutions"));
  });

  it("removes the resolutions again once yarn holds the result on its own", () => {
    const dir = makeProject();

    let duplicates = snapshot("leaf@npm:1.0.0", "leaf@npm:2.0.0");
    let converged = false;
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: (message = "") => logs.push(message),
      readFixes: () => [leafFix],
      readDuplicates: () => duplicates,
      verifyFrozen: () => 0,
      resolve: () => {
        if (read(dir, "package.json").includes('"leaf": "2.0.0"')) {
          converged = true;
        }
        // sticky: yarn keeps a locked resolution that still satisfies the range
        duplicates = converged ? snapshot() : duplicates;
        return 0;
      },
    });

    strictEqual(outcome.status, "applied");
    deepStrictEqual(outcome.stickyOverrides, []);
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes("Removing the resolutions")),
      true,
    );
  });

  it("writes the resolution for a member nothing duplicates that holds its family apart", () => {
    const dir = makeProject();
    const logs: string[] = [];
    let parentMoved = false;

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: (message = "") => logs.push(message),
      readFixes: () => [
        fix({
          applicable: true,
          target: "2.0.0",
          convergentMembers: ["leaf"],
          reResolutionSet: ["parent"],
        }),
      ],
      readDuplicates: () =>
        parentMoved ? snapshot() : snapshot("leaf@npm:1.0.0", "leaf@npm:2.0.0"),
      readVersions: () =>
        new Map([
          ["leaf", parentMoved ? ["2.0.0"] : ["1.0.0", "2.0.0"]],
          ["parent", [parentMoved ? "2.0.0" : "1.0.0"]],
        ]),
      verifyFrozen: () => 0,
      resolve: () => {
        // parent pins leaf exactly: the family only merges once parent moves
        if (read(dir, "package.json").includes('"parent": "2.0.0"')) {
          parentMoved = true;
        }
        return 0;
      },
    });

    strictEqual(outcome.status, "applied");
    ok(logs.includes('  "parent": "2.0.0" (converge)'));
    strictEqual(read(dir, "package.json"), manifestContent);
  });

  it("reverts and points at the issue tracker when a standing resolution is needed", () => {
    const dir = makeProject();

    const duplicated = snapshot("leaf@npm:1.0.0", "leaf@npm:2.0.0");
    let duplicates = duplicated;
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: (message = "") => logs.push(message),
      readFixes: () => [leafFix],
      readDuplicates: () => duplicates,
      verifyFrozen: () => 0,
      resolve: () => {
        // the duplicate only stays away while the resolution is there
        duplicates = read(dir, "package.json").includes('"leaf": "2.0.0"')
          ? snapshot()
          : duplicated;
        return 0;
      },
    });

    strictEqual(outcome.status, "reverted");
    deepStrictEqual(
      outcome.stickyOverrides.map((o) => o.packageName),
      ["leaf"],
    );
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes("github.com/christophehurpeau")),
      true,
    );
  });

  it("reverts when the result is not one `--immutable` accepts", () => {
    const dir = makeProject();

    let duplicates = snapshot("leaf@npm:1.0.0", "leaf@npm:2.0.0");
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: (message = "") => logs.push(message),
      readFixes: () => [leafFix],
      readDuplicates: () => duplicates,
      verifyFrozen: () => 1,
      resolve: () => {
        duplicates = snapshot();
        return 0;
      },
    });

    strictEqual(outcome.status, "reverted");
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes("--immutable")),
      true,
    );
  });

  it("reverts everything when the re-resolution fails", () => {
    const dir = makeProject();

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: () => undefined,
      readFixes: () => [metroFix],
      readDuplicates: () =>
        snapshot("metro-config@npm:0.84.5", "metro-config@npm:0.87.0"),
      verifyFrozen: () => 0,
      resolve: () => 1,
    });

    strictEqual(outcome.status, "reverted");
    strictEqual(read(dir, "package.json"), manifestContent);
  });

  // yarn resolutions are unconditional, so one the detector proposed from a
  // single requester's range cannot be written when another requester rejects it
  it("drops a resolution a third-party range rejects", () => {
    const dir = makeProject();
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      log: (message = "") => logs.push(message),
      readFixes: () => [
        fix({
          anchor: "0.84.5",
          reuseFixes: [
            {
              requester: "@tamagui/metro-plugin@npm:1.0.0",
              requesterName: "@tamagui/metro-plugin",
              packageName: "metro-config",
              range: "*",
              from: "0.87.0",
              to: "0.84.5",
            },
          ],
          externalConstraints: [
            {
              requester: "@react-native/community-cli-plugin@npm:0.87.0",
              requesterName: "@react-native/community-cli-plugin",
              packageName: "metro-config",
              range: "^0.87.0",
            },
          ],
        }),
      ],
      readDuplicates: () => snapshot("metro-config@npm:0.84.5"),
      verifyFrozen: () => 0,
      resolve: () => {
        throw new Error("a dropped resolution must not resolve");
      },
    });

    strictEqual(outcome.status, "nothing-to-do");
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes("Skipped resolution")),
      true,
    );
  });

  const metroFamilyFix = fix({
    ...metroFix,
    members: ["metro", "metro-config"],
    duplicatedMembers: ["metro-config"],
  });

  it("skips a cluster the filter only selects part of", () => {
    const dir = makeProject();
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      dryRun: true,
      log: (message = "") => logs.push(message),
      filter: { include: ["metro-config"] },
      readFixes: () => [metroFamilyFix],
      readDuplicates: () => snapshot("metro-config@npm:0.84.5"),
      verifyFrozen: () => {
        throw new Error("a dry run must not verify");
      },
      resolve: () => {
        throw new Error("a dry run must not resolve");
      },
    });

    strictEqual(outcome.plannedChangeCount, 0);
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes("metro not selected by the filter")),
      true,
    );
  });

  it("keeps a cluster the filter selects whole", () => {
    const dir = makeProject();

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      dryRun: true,
      log: () => undefined,
      filter: { include: ["metro*"] },
      readFixes: () => [metroFamilyFix],
      readDuplicates: () => snapshot("metro-config@npm:0.84.5"),
      verifyFrozen: () => {
        throw new Error("a dry run must not verify");
      },
      resolve: () => {
        throw new Error("a dry run must not resolve");
      },
    });

    ok(outcome.plannedChangeCount > 0);
  });

  it("writes nothing on a dry run", () => {
    const dir = makeProject();
    const logs: string[] = [];

    const outcome = applyClusterFixes({
      projectDir: dir,
      color: false,
      dryRun: true,
      log: (message = "") => logs.push(message),
      readFixes: () => [metroFix],
      readDuplicates: () => snapshot("metro-config@npm:0.84.5"),
      verifyFrozen: () => {
        throw new Error("a dry run must not verify");
      },
      resolve: () => {
        throw new Error("a dry run must not resolve");
      },
    });

    strictEqual(outcome.status, "dry-run");
    strictEqual(read(dir, "package.json"), manifestContent);
    strictEqual(
      logs.some((line) => line.includes('"0.84.5" -> "0.87.0"')),
      true,
    );
    strictEqual(
      logs.some((line) => line.startsWith("Would apply:")),
      true,
    );
    ok(outcome.plannedChangeCount > 0);
  });

  it("reports having nothing to do when no fix is applicable", () => {
    const dir = makeProject();

    strictEqual(
      applyClusterFixes({
        projectDir: dir,
        color: false,
        log: () => undefined,
        readFixes: () => [fix({ applicable: false })],
        readDuplicates: () => snapshot("leaf@npm:1.0.0"),
        verifyFrozen: () => 0,
        resolve: () => {
          throw new Error("nothing to apply must not resolve");
        },
      }).status,
      "nothing-to-do",
    );
  });
});
