import * as yarnParsers from "@yarnpkg/parsers";

export interface YarnEntry {
  version: string;
  resolution?: string;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  dependenciesMeta?: Record<string, Record<string, unknown>>;
  peerDependenciesMeta?: Record<string, Record<string, unknown>>;
  bin?: Record<string, string>;
  checksum?: string;
  conditions?: string;
  languageName?: string;
  linkType?: "hard" | "soft";
}

export interface YarnMetadata {
  version: string;
  cacheKey?: string;
}

/**
 * `__metadata` sits in the same map as the packages but is not one, so every
 * pass reads the entries through `packageEntries` rather than re-testing the
 * key and casting.
 */
export type YarnEntries = Record<string, YarnEntry | YarnMetadata>;

export const packageEntries = (
  entries: YarnEntries,
): [entryKey: string, entry: YarnEntry][] =>
  Object.entries(entries).filter(
    (entry): entry is [string, YarnEntry] => entry[0] !== "__metadata",
  );

export const parseYarnLock = (content: string): YarnEntries =>
  yarnParsers.parseSyml(content);

const yarnLockHeader = `${[
  `# This file is generated by running "yarn install" inside your project.\n`,
  `# Manual changes might be lost - proceed with caution!\n`,
].join("")}\n`;

export const stringifyYarnLock = (entries: YarnEntries): string =>
  yarnLockHeader + yarnParsers.stringifySyml(entries);
